site_name: The Social Game
site_description: An examination of social programming, digital manipulation, and
  the construction of collective reality.
site_author: Rez Khan
site_url: https://universalbookcompiler.com/20_The_Social_Game/
site_dir: ../site_build
docs_dir: docs
nav:
- index.md
- The Social Game: the-social-game.md
- 'Part 1: The Lost Art of Community':
  - part-1-the-lost-art-of-community.md
  - chapter-1-the-mystery-of-thriving-communities.md
  - chapter-2-the-social-mirror-how-healthy-identity-forms.md
  - chapter-3-evidence-file-1-the-divide-and-conquer-phenomenon.md
  - chapter-4-true-hierarchy-vs-false-hierarchy-how-natural-learning-communities-develop.md
  - chapter-5-evidence-file-2-the-perpetual-adolescence-mystery.md
  - chapter-6-beyond-good-and-evil-a-new-framework-for-ethics.md
  - chapter-7-the-internets-false-democracy.md
  - chapter-8-the-modern-disruption.md
  - chapter-9-chapter-4.md
  - chapter-10-the-elite-alliance-pattern-weaponizing-the-weaker-against-the-stronger.md
  - chapter-11-the-mystery-of-thriving-communities.md
- 'Part 2: The Social Game':
  - part-2-the-social-game.md
  - chapter-12-investigation-report-1-the-social-mirror-phenomenon.md
  - chapter-13-true-hierarchy-vs-false-equality.md
  - chapter-14-the-digital-hijacking.md
  - chapter-15-the-scale-dependent-nature-of-social-systems.md
- 'Part 3: The Cultural Game':
  - part-3-the-cultural-game.md
  - chapter-16-the-creative-trap.md
  - chapter-17-cultural-analysis-1-the-science-authority-deception.md
  - chapter-18-practices-as-resistance-daily-actions-that-undermine-social-programming.md
- 'Part 4: The Meta-Game':
  - part-4-the-meta-game.md
  - chapter-19-solution-integration-1-the-endless-game.md
  - chapter-20-cultural-preservation-and-creation-building-sacred-community-in-a-secular-age.md
  - chapter-21-practical-implementation-guide-building-your-upward-spiral.md
  - chapter-22-glossary-of-terms.md
- Downloads: downloads/index.md
theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  - content.tabs.link
  font:
    text: Inter
    code: Fira Code
plugins:
- search
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.details
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- codehilite
- toc
- tables
- footnotes
- attr_list
- md_in_html
extra_css:
- stylesheets/custom.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DoctorKhan/Universal-Book-Compiler
copyright: Copyright &copy; 2025 Rez Khan
