site_name: The Social Game
site_description: An examination of social programming, digital manipulation, and
  the construction of collective reality.
site_author: Rez Khan
site_url: https://universalbookcompiler.com/10_The_Social_Game/
site_dir: ../site_build
docs_dir: docs
nav:
- index.md
- The Social Game: the-social-game.md
- Part I Intro:
  - part-1-part-i-intro.md
  - chapter-1-social-mirror.md
  - chapter-2-divide-and-conquer.md
  - chapter-3-true-vs-false-hierarchy.md
  - chapter-4-hollow-middle-architecture-isolation.md
  - chapter-5-rites-of-passage.md
  - chapter-6-field-manual-three-spheres-audit.md
  - chapter-7-war-room-discovery-divide-and-conquer.md
  - chapter-8-internets-false-democracy.md
  - chapter-9-investigator-roundtable-lost-architecture.md
  - chapter-10-parable-marionette-strings.md
  - chapter-11-reality-whirlpool-first-aid.md
  - chapter-12-investigator-roundtable-who-benefits.md
  - chapter-13-the-great-forgetting.md
  - chapter-14-investigators-converge.md
  - chapter-15-science-as-verification.md
  - chapter-16-part-4-the-meta-game.md
- 'Part 4: The Meta-Game':
  - part-2-the-meta-game.md
  - chapter-17-practical-implementation-guide.md
  - chapter-18-meta-game.md
  - chapter-19-the-unsolved-mystery.md
  - chapter-20-counter-strategy-principles.md
  - chapter-21-the-war-on-play.md
  - chapter-22-sovereign-mind-principles.md
  - chapter-23-science-of-sovereign-connection.md
  - chapter-24-strategists-dilemma.md
  - chapter-25-glossary-of-terms.md
  - chapter-26-the-investigators.md
- Downloads: downloads/index.md
theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  - content.tabs.link
  font:
    text: Inter
    code: Fira Code
plugins:
- search
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.details
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- codehilite
- toc
- tables
- footnotes
- attr_list
- md_in_html
extra_css:
- stylesheets/custom.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DoctorKhan/Universal-Book-Compiler
copyright: Copyright &copy; 2025 Rez Khan
