site_name: The Social Game
site_description: An examination of social programming, digital manipulation, and
  the construction of collective reality.
site_author: Rez Khan
site_url: https://universalbookcompiler.com/10_The_Social_Game/
site_dir: ../site_build
docs_dir: docs
nav:
- index.md
- The Social Game: the-social-game.md
- Part I Intro:
  - part-1-part-i-intro.md
  - chapter-1-clue-from-the-east-the-balinese-resilience.md
  - chapter-2-principle-1-the-social-rhythm.md
  - chapter-3-clue-from-the-festival-the-power-of-play.md
  - chapter-4-principle-2-playful-sovereignty-the-purpose-of-passage.md
  - chapter-5-clue-from-the-workshop-a-tale-of-two-hierarchies.md
  - chapter-6-field-manual-three-spheres-audit.md
  - chapter-7-principle-3-true-vs-false-hierarchy.md
  - chapter-8-clue-from-the-pacific-the-hawaiian-flow.md
  - chapter-9-parable-marionette-strings.md
  - chapter-10-principle-4-the-architecture-of-natural-belonging.md
  - chapter-11-reality-whirlpool-first-aid.md
  - chapter-12-the-great-forgetting.md
  - chapter-13-war-room-discovery-ancient-playbook.md
  - chapter-14-divide-conquer-architecture-division.md
  - chapter-15-hollow-middle-architecture-isolation.md
  - chapter-16-digital-accelerant-false-democracy.md
  - chapter-17-science-as-verification.md
  - chapter-18-part-4-the-meta-game.md
- 'Part 4: The Meta-Game':
  - part-2-the-meta-game.md
  - chapter-19-practical-implementation-guide.md
  - chapter-20-meta-game.md
  - chapter-21-the-unsolved-mystery.md
  - chapter-22-counter-strategy-principles.md
  - chapter-23-the-war-on-play.md
  - chapter-24-sovereign-mind-principles.md
  - chapter-25-science-of-sovereign-connection.md
  - chapter-26-strategists-dilemma.md
- 'Appendix B: Practical Exercises':
  - chapter-27-appendix-b-exercises-overview.md
  - chapter-28-exercise-b1-flotilla-formation.md
  - chapter-29-exercise-b2-three-spheres-audit.md
  - chapter-30-exercise-b3-string-identification.md
  - chapter-31-exercise-b4-three-doors-practice.md
  - chapter-32-exercise-b5-30-day-field-manual.md
- 'Appendix C: Reference':
  - chapter-28-glossary-of-terms.md
  - chapter-29-the-investigators.md
- Downloads: downloads/index.md
theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.highlight
  - search.share
  - content.code.copy
  - content.action.edit
  - content.action.view
  - content.tabs.link
  font:
    text: Inter
    code: Fira Code
plugins:
- search
markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.details
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- codehilite
- toc
- tables
- footnotes
- attr_list
- md_in_html
extra_css:
- stylesheets/custom.css
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DoctorKhan/Universal-Book-Compiler
copyright: Copyright &copy; 2025 Rez Khan
